# Generated by Django 2.0.7 on 2018-07-13 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('rate', models.IntegerField(default=1)),
                ('property_for_rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.Property')),
            ],
        ),
    ]
